// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMhDui9a0DzPqv2f3e_dnA6aE9c8P0Ni4',
    appId: '1:264133774332:web:0cf0761be7881ea3368079',
    messagingSenderId: '264133774332',
    projectId: 'bike-rent-8687d',
    authDomain: 'bike-rent-8687d.firebaseapp.com',
    storageBucket: 'bike-rent-8687d.appspot.com',
    measurementId: 'G-BZTEEKHYWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0NNzMwLjhk96ZOwMQNyq2WXGpPTxBm3Q',
    appId: '1:264133774332:android:17b9b1edf210a2a8368079',
    messagingSenderId: '264133774332',
    projectId: 'bike-rent-8687d',
    storageBucket: 'bike-rent-8687d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMvErL8Y9DuKCy4a3V5q1LCwVxX1OB39A',
    appId: '1:264133774332:ios:dc563ba8fd6bf4c4368079',
    messagingSenderId: '264133774332',
    projectId: 'bike-rent-8687d',
    storageBucket: 'bike-rent-8687d.appspot.com',
    iosClientId: '264133774332-buksiflfo5272vcq5m2juhs25g04ieiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
